name = "MCC Island"
author = "barraIhsan"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c987b1f18396a04eb4abb48e28dfc60884be8f2a2018bf305490f88a29de5fdd"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
